packages:
  - themes/*
  - packages/*
  - scripts

engineStrict: true
strictPeerDependencies: true
shellEmulator: true
preferWorkspacePackages: true
linkWorkspacePackages: true
enablePrePostScripts: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@deox/*"
  - "blogger-images"

catalog:
  "@tsdown/css": "^0.22.3"
  "@types/node": "^26.1.0"
  "@types/react": "^19.2.17"
  "@types/react-dom": "^19.2.3"
  blogger-plugin: "^0.0.13"
  react: "^19.2.7"
  react-dom: "^19.2.7"
  svelte: "^5.56.4"
  tsdown: "^0.22.3"
  vite: "^8.1.3"

allowBuilds:
  "@firebase/util": true
  "@swc/core": true
  esbuild: true
  msw: true
  protobufjs: true
  svelte-preprocess: true
